### ISSUE TITLE
Can you support workspaces please?

### ISSUE THREAD

**Issue by murbanowicz** [vasilevich/sync-yarnlock-into-packagejson#6] opened 2018-12-20 18:39 UTC
Could you support workspaces?

**Comment by vasilevich** [comment] 2018-12-20 19:44
Hi, thank you for your question, may you please provide an example of package.json+ yarn.lock as an input, and the output you expect to have, so I can understand what it is?  you can just put 1 package in it.

or explain in any other way you like, what exactly is missing. thanks.

**Comment by vasilevich** [comment] 2019-03-20 16:29
seems like it is not important to you, as I didn't hear from you for months, so I'll close this issue, 
if its still relevant feel free to reopen it with an answer to my question

thanks and best of luck.

**Closed by vasilevich** 2019-03-20 16:29 UTC

**Comment by merceyz** [comment] 2019-07-15 13:34
Since he didn't respond, I'll provide an answer to get this going

> please provide an example of package.json+ yarn.lock as an input

https://github.com/mui-org/material-ui

> the output you expect to have

Running `syncyarnlock -s -k` in the root folder I expect it to follow the paths in the `workspaces` field and update all packages at those paths

**Comment by vasilevich** [comment] 2019-07-15 15:39
@merceyz Hey thanks for explaining,  just to reiterate, you would like the program to check whether package.json has "workspaces"  and then enter each path, and see what packages are there, grab their package.json and extract their npm module name + version and then insert it into the dependencies ?

I guess it is possible , but are you sure its related to the scope of this project? (sync yarn to package json)
I will be glad to do that in a seperate similar project maybe under the name sync work space into packagejson?  it just doesn't make sense to me to implement it in sync yarn to package json.

please let me know if I misunderstood or you have a better idea and I will be glad to get it done.

cheers

**Comment by merceyz** [comment] 2019-07-15 15:52
> and see what packages are there, grab their package.json and extract their npm module name + version and then insert it into the dependencies ?

No, I would like it to sync the versions from yarn.lock into those packages as well.

Basically want it to do this:
```
syncyarnlock -d . -p .
syncyarnlock -d . -p ./packages/package-a
syncyarnlock -d . -p ./packages/package-b
syncyarnlock -d . -p ./packages/package-c
...
```

Where it grabs the paths from the `workspaces` field

**Comment by vasilevich** [comment] 2019-07-15 16:28
the problem is, I don't understand where in the yarnlock these "workspaces" are or how are they even called.  I opened yarn.lock and searched for the keyword "workspaces" but nothing comes up. 
can you please link to yarnlock line, or say what line in yarnlock defines this path?  how do I know it is a workspace and not a normal module?


thanks

**Comment by merceyz** [comment] 2019-07-15 16:55
Oh, it's in the root `package.json` file

Example: https://github.com/mui-org/material-ui/blob/b198da072707eb6da1b5579b35eba989e26a6be4/package.json#L220-L223

**Comment by vasilevich** [comment] 2019-07-15 17:22
I went inside packages folder: https://github.com/mui-org/material-ui/tree/b198da072707eb6da1b5579b35eba989e26a6be4/packages

and for example I took the name material-ui-codemod  and searched in yarn.lock,  and didn't find
moreover I went inside the package folder package.json and took the name @material-ui/codemod and couldn't find that in yarn.lock either.

so what should I do with yarn lock? these packages are simpley not there.

sorry I just don't understand what to do you will have to be more specific.

thanks

**Comment by merceyz** [comment] 2019-07-15 18:42
I just made a PR that adds support for workspaces, easier than explaining.

**Comment by vasilevich** [comment] 2019-07-15 19:04
@merceyz Sorry for my lack of understanding, I am just not familiar with workspaces yet.
Thank you for the pr. I have accepted it and published to npm aswell

**Comment by merceyz** [comment] 2019-07-15 19:05
No worries, thanks!
